
const types = {
  LOAD_DATA_MOVIE_SUCCESS: 'LOAD_DATA_MOVIE_SUCCESS',
  LOAD_DATA_MOVIE_FAILED: 'LOAD_DATA_MOVIE_FAILED',
  LOAD_DATA_MOVIE_DETAIL_SUCCESS: 'LOAD_DATA_MOVIE_DETAIL_SUCCESS',
  LOAD_DATA_MOVIE_DETAIL_OLD_SUCCESS: 'LOAD_DATA_MOVIE_DETAIL_OLD_SUCCESS',
  LOAD_DATA_MOVIE_DETAIL_FAILED: 'LOAD_DATA_MOVIE_DETAIL_FAILED',
  LOAD_DATA_MOVIE_SEARCH_NAVBAR_SUCCESS: 'LOAD_DATA_MOVIE_SEARCH_NAVBAR_SUCCESS',
  LOAD_DATA_MOVIE_SEARCH_NAVBAR_FAILED: 'LOAD_DATA_MOVIE_SEARCH_NAVBAR_FAILED',
  RESET_DATA_MOVIE_SEARCH_NAVBAR: 'RESET_DATA_MOVIE_SEARCH_NAVBAR',
  LOAD_DATA_MOVIE_SEARCH_SUCCESS: 'LOAD_DATA_MOVIE_SEARCH_SUCCESS',
  LOAD_DATA_MOVIE_SEARCH_FAILED: 'LOAD_DATA_MOVIE_SEARCH_FAILED',
  LOAD_DATA_PERSON_SEARCH_SUCCESS: 'LOAD_DATA_PERSON_SEARCH_SUCCESS',
  LOAD_DATA_PERSON_SEARCH_FAILED: 'LOAD_DATA_PERSON_SEARCH_FAILED',
  CHANGE_PAGE_TO: 'CHANGE_PAGE_TO',
  RESET_DATA_MOVIE_SEARCH: 'RESET_DATA_MOVIE_SEARCH',
  RESET_DATA_PERSON_SEARCH: 'RESET_DATA_PERSON_SEARCH',
}

export default types